formatter: markdown table

header-from: main.tf


output:
  file: "README.md"
  mode: replace
  template: |-
    # Terraform Cloudflare R2 API Token

    Terraform module to create a Cloudflare API token that have bucket scope permissions.
    The API token needed by the Cloudflare provider needs to have `User -> API Tokens -> Edit token` permissions. You can use [this quick link](https://dash.cloudflare.com/profile/api-tokens?permissionGroupKeys=%5B%7B%22key%22%3A%22api_tokens%22%2C%22type%22%3A%22edit%22%7D%5D&name=R2+API+Token+Module&accountId=*&zoneId=all) to create the token with the correct permissions.

    Example:
    
    ```hcl
    module "r2-api-token" {
      source  = "Cyb3r-Jak3/r2-api-token/cloudflare"
      version = "<version>"
      account_id = "<account>"
      buckets = ["bucket-1", "bucket-2"]
      write = false
    }
    ```

    ### Cloudflare provider version support
    6.0 and above uses version 5.13 and above of the Cloudflare provider.
    5.0 and above uses version 5.0 of the Cloudflare provider.  
    4.1.1 and below uses version 4 of the Cloudflare provider.

    I will continue to support the 4.1.1 version to the best of my ability, but I will not be adding new features to it. I will only add new features to the 5.0 version of the provider.
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->


settings:
  lockfile: false
  read-comments: true
  sensitive: true