name: Terraform Testing

on: [push]


jobs: 
  Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/testing
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
    
      - name: Terraform Destroy
        run: terraform destroy -auto-approve

