name: Terraform Testing

on: 
  pull_request:
    branches: [ main ]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v4
          with:
            go-version: '1.20'
        
        - uses: hashicorp/setup-terraform@v3
        
        - name: Install Terraform Docs
          run: |
              go install github.com/terraform-docs/terraform-docs@v0.17.0

        - name: Terraform Docs
          run: |
              terraform-docs --output-check .
        
        - name: Terraform Format Check
          run: |
              terraform fmt -check -recursive

  Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/testing
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            TF_VAR_account_id: ${{ secrets.TF_VAR_ACCOUNT_ID }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        if: always()
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            TF_VAR_account_id: ${{ secrets.TF_VAR_ACCOUNT_ID }}


